// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1SFipz-CjkfRUIGYXW4NEHeIzAcgNcQ',
    appId: '1:1062563501750:web:e36bd2d34f19f1318d3817',
    messagingSenderId: '1062563501750',
    projectId: 'quizapp-779b6',
    authDomain: 'quizapp-779b6.firebaseapp.com',
    storageBucket: 'quizapp-779b6.firebasestorage.app',
    measurementId: 'G-92NTF68M69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6tWKyofi37IDGLIRy10vL3KS7ZAS2EY',
    appId: '1:1062563501750:android:3dddb8a8e5df45fb8d3817',
    messagingSenderId: '1062563501750',
    projectId: 'quizapp-779b6',
    storageBucket: 'quizapp-779b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmWliD9sDASj0ChlJSWyBavWHZ94SujU',
    appId: '1:1062563501750:ios:0dedf7b458d411108d3817',
    messagingSenderId: '1062563501750',
    projectId: 'quizapp-779b6',
    storageBucket: 'quizapp-779b6.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmWliD9sDASj0ChlJSWyBavWHZ94SujU',
    appId: '1:1062563501750:ios:0dedf7b458d411108d3817',
    messagingSenderId: '1062563501750',
    projectId: 'quizapp-779b6',
    storageBucket: 'quizapp-779b6.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU1SFipz-CjkfRUIGYXW4NEHeIzAcgNcQ',
    appId: '1:1062563501750:web:143e7f1731044db78d3817',
    messagingSenderId: '1062563501750',
    projectId: 'quizapp-779b6',
    authDomain: 'quizapp-779b6.firebaseapp.com',
    storageBucket: 'quizapp-779b6.firebasestorage.app',
    measurementId: 'G-RN217SY2D7',
  );
}
